# model_type: 'AutoEncoderDeconvolution'
# model_type: 'CNN_4L'
model_type: 'CNN_small'

lr: 0.001
batch_size: 64

stopping_params:
  'num_epochs': 50
  'patience': 12
  'tolerance': 0.0001

criterion_params:
  'alpha': 85.0
  'lambda_tv': 0.00001

scheduler_params:
  'patience': 5
  'threshold': 0.001
  'factor': 0.5
